name: Latest Blog Posts

on:
  schedule:
    - cron: '0 0 * * *'  # æ¯å¤©æ›´æ–°ä¸€æ¬¡
  workflow_dispatch:  # å…è®¸æ‰‹åŠ¨è§¦å‘

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Update README with Juejin posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://juejin.cn/user/4100551259985721"
          max_post_count: 5
          template: "$newline- $randomEmoji(ğŸ’¯,ğŸ”¥,ğŸ’«,ğŸš€,ğŸŒŸ) [$title]($url) $newline"